### ISSUE TITLE
base85 encode/decode doesn't work

### ISSUE THREAD

**Issue by ronaaron** [calzakk/CyoEncode#3]
As per this code:
````
#include <stdio.h>

#include "CyoEncode.h"
#include "CyoDecode.h"


int main(int argc, char ** argv)
{
	const char instr[] = "Hello, world!";
	char * b85 = (char*) malloc(cyoBase85EncodeGetLength(sizeof(instr))+1);
	size_t b85_len = cyoBase85EncodeA(b85, instr, sizeof(instr));

	printf("Encoded b85 [%.*s]\n", (int) b85_len, b85);

	char *decoded = (char *) malloc(cyoBase85DecodeGetLength(b85_len) + 1);
	size_t decoded_len = cyoBase85DecodeA(decoded, b85, b85_len);
	printf("Decoded b85 [%.*s]\n", (int) decoded_len, decoded);
	return 0;
}
````

The 'decoded_len' is 0.

**Comment by ronaaron** [comment]
I think the encoding is faulty, as it returns an 18 byte string when it should be a multiple of 5.

**Comment by calzakk** [comment]
Hi @ronaaron, apologies for the late reply!

There's indeed a bug in the base85 decoding, which I fixed and committed a little while ago - just pull or download the latest version.
Also, in your test code, you could use strlen instead of sizeof, otherwise the trailing null terminator will be included in the encoded output (and also note the addition of decoded[decoded_len] = '\0' to terminate the decoded output):

```
#include <stdio.h>
#include <string.h> //NEW

#include "CyoEncode.h"
#include "CyoDecode.h"

int main(int argc, char** argv)
{
	const char instr[] = "Hello, world!";
	char* b85 = (char*)malloc(cyoBase85EncodeGetLength(strlen(instr)) + 1); //STRLEN
	size_t b85_len = cyoBase85EncodeA(b85, instr, strlen(instr)); //STRLEN

	printf("Encoded b85 [%.*s]\n", (int)b85_len, b85);

	char* decoded = (char*)malloc(cyoBase85DecodeGetLength(b85_len) + 1);
	size_t decoded_len = cyoBase85DecodeA(decoded, b85, b85_len);
	decoded[decoded_len] = '\0';  //NEW
	printf("Decoded b85 [%.*s]\n", (int)decoded_len, decoded);
	return 0;
}
```

**Comment by calzakk** [comment]
> I think the encoding is faulty, as it returns an 18 byte string when it should be a multiple of 5.

Actually, it doesn't necessarily have to be a multiple of 5 characters. Five zero bytes can be output as a single 'z' character (see the FOLD_ZERO option). And the last bytes of the input can be encoded as 2-5 chars.  Part of the fix was to eliminate the multiple-of-5 check!

**Comment by ronaaron** [comment]
Thanks.

My fussy compiler is complaining:

     src/CyoDecode.c:1133:20: error: assigning to 'const char *' from incompatible type 'const void *'
            pSrc = cyoBase85NextByte(pSrc, &in1, &padding);

**Comment by calzakk** [comment]
Just committed a fix, now builds correctly using GCC.
Which compiler are you using?

**Comment by ronaaron** [comment]
Thanks, it builds fine for me now (and base85 passes my tests!).  Using 'clang' with warnings cranked up.

**Comment by calzakk** [comment]
Thanks for confirming :)
